hash-format = "sha256"

[[files]]
file = "config/defaultoptions/extra/automodpack/automodpack-client.json"
hash = "240e6574d2ed5210f38500d76acf62b974c66319ca7fdcc94046a362cf7b819e"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "ad01af66b226cd0b065e06b1a5301c3d14107cb9f8063576779bc4c0057c1101"

[[files]]
file = "mods/automodpack.pw.toml"
hash = "68c6403adbe1e00a52faee4f95fc38a55f167c760df2d9fc7b7eeef996847c54"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5d0603e338ddb39ddbac6c1732639c6b55c968e6a9dc9aab981dcae5ad3c34cf"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "024c19f7da29f18d59bfc3dd0344b611e5acdf28f90c0f9e73295f20e67e493f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "servers.dat"
hash = "8f18563bc567e7ea8955255712bb4d651c52a78fac30e5c7cd66fc4aa746b46c"
