hash-format = "sha256"

[[files]]
file = "automodpack/automodpack-server.json"
hash = "09586aa007ab48c8c106d12d14a227e36438925887ab2b12b2c6256e45d2361c"

[[files]]
file = "config/defaultoptions/extra/automodpack/automodpack-client.json"
hash = "240e6574d2ed5210f38500d76acf62b974c66319ca7fdcc94046a362cf7b819e"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "ad01af66b226cd0b065e06b1a5301c3d14107cb9f8063576779bc4c0057c1101"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "b1f392d56c527e657c9b37eaf0fc6967f8c95c167c3e925fcf4518bdd4dd96af"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "2b16d6b699429794cd0acf2c93011ac90d21f97fb52d927dbde43ae903b7049a"

[[files]]
file = "config/universal-graves/config.json"
hash = "c2a938eddadd498ee4675b982e16eafaebe6db9478254fffedfba0f8f9ea8587"

[[files]]
file = "eula.txt"
hash = "ee27072e4a23e088522f740ddaab0c7c4145c186969e90a86254faa3a5ec5ce6"

[[files]]
file = "mods/RoughlyEnoughItems-21.9.9999-fabric.jar"
hash = "3a4cdb86f1ba1ca5e4ddb10d73d6f6e9f27818d973497bfe3a1ba5baca210000"

[[files]]
file = "mods/advanced-shulkerboxes.pw.toml"
hash = "406d162be23119672b8130070879fac9bc8beaa4d574db3fbdf9d76ead165fa5"
metafile = true

[[files]]
file = "mods/anvil-restoration.pw.toml"
hash = "f413681136c633b276e074f610629e0551e024acb60ff34faf50fdb5105a892e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6187b9cadca608c7d1a00c9fe3a826a2dbfa20f089235147fc9bcfdd85f0c250"
metafile = true

[[files]]
file = "mods/automodpack.pw.toml"
hash = "0dce740fbf6f233f7be8301352832899d23807f6ba205412d959f7c2d5822505"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "4cb213110c1b7ffa19494486d06fe28d02d1121b702415e9a6394d8e00c4326b"
metafile = true

[[files]]
file = "mods/better-animations-collection.pw.toml"
hash = "b4f7f39914c51ae14d980e48906bc309442373581258c8a991b435ad5f10c0cc"
metafile = true

[[files]]
file = "mods/block-runner.pw.toml"
hash = "cfdc6367f34ce1439549faefa47412d39cf5e188dacac06b068064a7ba48f3f8"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "4a9910d74bb7a85600abaf36ae568bcfb10e76062b9d5d718656f5d172e79419"
metafile = true

[[files]]
file = "mods/chunks-fade-in.pw.toml"
hash = "6955491d128a11ca3c49dea296d2d3db48cc9301b561100191daca74c0b567f4"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "e2013d8427722fce9a1b3c07a0720fd0d80d0a378269dd8364fd5e6d6f9dd094"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "b683db7d507c3bac95b1ba7664d49062d59bea8e4ab131d7d1ceac4a8994298f"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "001e8854fc3e5e81d168944d8f32f1eb5f27a4808131783d647dbaf7824b9dd3"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "5b68880f4f5606aa7848d5b1ed9fbb7351a41094a3e5d1090d943b85a5d8bc0a"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "68d83de0de41e1f28165a6dbd932319e8c8b46461b6a0fecf2dd3360091d34b9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "48a71da0cd96100ccc239fa88fb6280094f0a0b1a555a2bdcc2e58dc2d7ebcc5"
metafile = true

[[files]]
file = "mods/fast-sleep.pw.toml"
hash = "b3871250705bf7aaf3bbed053e13469d74847ac9681e357f3d9304a9ce57b41d"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "fceeee5b54a4cbdf5bddf6a7d12739d9bf3a1c59ee6608211b0c6fbde91b740f"
metafile = true

[[files]]
file = "mods/inventory-management.pw.toml"
hash = "b50651c2c054ff67985150b5a80198fda6606545f7d68e92548d1a7fea4c0914"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "471c02eac5adf025ed2246c2d3efd8267c67574f1bc7329b49caa1ada17fbc9e"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "625843fd6f3fc3b38460f00ecc91665714d58928f48b8ca2d653eb84fa173a98"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7fc67cabd5de89ebe9d7d995cdf160ceff0572c2bef784e846675976a428c9fa"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "8709d16a07caea1962d2cbf1b3ae1f156de3f78bc15dcd4af9d26010518567a1"
metafile = true

[[files]]
file = "mods/mns-moogs-nether-structures.pw.toml"
hash = "37e37d378573a64b1f00b81f7bf96071a053a387d70da2e29471315e98a029c7"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "f72424bc6de445e9fb683438b5e27c1a678b4718383157dba2428b84f39d5130"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "383098e1c971e33f71aeb2b6907d8734f4b42db4e6a26aec51166e232c33b153"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "dc24a4cc0ad484d6593997c197ea602fac4d98c45dab0de6421e704c3851acd9"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "c0b691fa58c8a7177fa08fe8577324f82bae5b120f80c21a1b38fa2fe55e7e84"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "553d25687e97d438dd82bd091a431602c1fb82d1def1bf86559461ceb3cc3101"
metafile = true

[[files]]
file = "mods/no-realms-button.pw.toml"
hash = "82c5501ec0543e249a0b3efcd3b66e517c9842aeeebd807a9c40fb7738d5a647"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
hash = "0428f42a616c2e4052524cd156316a25abf6bffc752c36278aac19d0c3137cdd"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "2b249557994541ab81f7517728fe0c65b8a11686bcc76b29bb3a95b1918a46a8"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "9b992b32fb5d6f5487f18ab3039f2b1cdcda0728e5b059445a55271d36f365da"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "019737abe9c9d7ef3638556e810babc2a3258a5c9be6cc15b79f780e71db7fa9"
metafile = true

[[files]]
file = "mods/resource-config-api.pw.toml"
hash = "2d911f54fa9e9f6abfb862008c9ece4fd91fee0d1e26de91c9843c978c4c71df"
metafile = true

[[files]]
file = "mods/resource-library.pw.toml"
hash = "61b6a2295dece08d74a098f03b16655417fe47b9de9fc3dfead08903d7671322"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
hash = "17f1f78051aab0bb1b9855f9756ca41fe14aaefcedd8a3b772d8a9619d675794"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8c961dbadf2dde334c857d0b42a6c6452aa77a146cf80d4febf7f46e4ac2ef6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ae52c6ae8a2f2e6ab55d9387e0fa25447f62866fed9acc5758acfb8b1907eabf"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "9210da9646623ee52aaa1bd7b52de6b02bd94ab70079bab6fa73c60ca89456fe"
metafile = true

[[files]]
file = "mods/sswaystones.pw.toml"
hash = "5c38cd80c30b9d64def3d0f2dd7a23a46dffeb323eeae2486f30bc4117b44d37"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "ed9329edc09aae7041d14e6f68563b9235a10163e4fc9e4e31d5a2d81883845e"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "9d181dd1c55864d941b06404652a76b385eb7dec0a71039fcbe8f681e1b2c550"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "61d853a4f2d353ac126a8196414efc82d0ca0402da2a8e492383dd539bfe4976"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "993390d4661a77aa83c8416f75addfccaf7cee0a7a7311a21742b2036700b5ac"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "53c8bc02c9b10610c43fc29127039036217e33a95ab2ea2d6ac291987266ef89"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "server-icon.png"
hash = "5982a4f9e0aa2895ab359e82924682312cb8d503cda392465bcdab3fa62b470e"

[[files]]
file = "server.properties"
hash = "fe9930a585899419fa5f6b99e65bca3a56c587864e9b6b90223ea2ed0a7437ee"

[[files]]
file = "servers.dat"
hash = "8f18563bc567e7ea8955255712bb4d651c52a78fac30e5c7cd66fc4aa746b46c"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true

[[files]]
file = "shaderpacks/miniature-shader.pw.toml"
hash = "5f0ce148b26430f53d74c88335b8a9412a085d8c24415e5a66123e106957dd5e"
metafile = true

[[files]]
file = "shaderpacks/super-duper-vanilla.pw.toml"
hash = "a8d349403d1c4b03c42f1962ba993e8b3dd65b9176176eec256f3fc6cbd9f40a"
metafile = true
