hash-format = "sha256"

[[files]]
file = "automodpack/automodpack-server.json"
hash = "503f1423d3bed8b463173b4f400707558ae00899417d531e5dfad979540fc0f8"

[[files]]
file = "config/defaultoptions/extra/automodpack/automodpack-client.json"
hash = "240e6574d2ed5210f38500d76acf62b974c66319ca7fdcc94046a362cf7b819e"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "ad01af66b226cd0b065e06b1a5301c3d14107cb9f8063576779bc4c0057c1101"

[[files]]
file = "config/euphoria_patcher.properties"
hash = "b1f392d56c527e657c9b37eaf0fc6967f8c95c167c3e925fcf4518bdd4dd96af"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "2b16d6b699429794cd0acf2c93011ac90d21f97fb52d927dbde43ae903b7049a"

[[files]]
file = "config/universal-graves/config.json"
hash = "c2a938eddadd498ee4675b982e16eafaebe6db9478254fffedfba0f8f9ea8587"

[[files]]
file = "eula.txt"
hash = "ee27072e4a23e088522f740ddaab0c7c4145c186969e90a86254faa3a5ec5ce6"

[[files]]
file = "mods/RoughlyEnoughItems-21.11.9999-fabric.jar"
hash = "71fb14312db83bc4392dae39ff0b0a80bf8f61be9b787992c2a5337d0d26616a"

[[files]]
file = "mods/advanced-shulkerboxes.pw.toml"
hash = "2cb5fa282c6bbd1bd6f59b0423f2579c8983458f9156f46902d1ff909232d454"
metafile = true

[[files]]
file = "mods/anvil-restoration.pw.toml"
hash = "0d34960baed7c58a163f21c70bbba1cec303f6499d5f6e2cffedd7c358dab1d5"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ed50f3b3feba91fa31915aefb40690bc322f37be83490e6b59a443e83a46a542"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff1763afa21669a76a9ca65735944986ec4ef7a0d440b98ee2154aafa46356c8"
metafile = true

[[files]]
file = "mods/automodpack.pw.toml"
hash = "68c6403adbe1e00a52faee4f95fc38a55f167c760df2d9fc7b7eeef996847c54"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5d0603e338ddb39ddbac6c1732639c6b55c968e6a9dc9aab981dcae5ad3c34cf"
metafile = true

[[files]]
file = "mods/better-animations-collection.pw.toml"
hash = "e1dce0606ea83226c448a30dfef8233a1952ee81c5d9395391e569cbbf98fb13"
metafile = true

[[files]]
file = "mods/block-runner.pw.toml"
hash = "10387e4aa22cd94d010086aa120770ff9d678897cc236a03c475acd3332c2532"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "092508af534efeb380b9551663980ab1f701d88583a63227d02cb02843335f7a"
metafile = true

[[files]]
file = "mods/chunks-fade-in.pw.toml"
hash = "c1e11404f33dd9828e8eb7126860e2c006be5dc1780e49c21b3275d08247b6bf"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "c30510e602ea1da542c6e94d00c9ee8cef39f4676ccc6792682c769fcd613cd5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "024c19f7da29f18d59bfc3dd0344b611e5acdf28f90c0f9e73295f20e67e493f"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "584c4c1c6f904156678e5eda999e959ca37df894dbb720b407993e01acd3eb58"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "76ba469ba67cdf17276da7a629ff85518f4c1dfaaae5ad28d9ee2d6bc79439c5"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "mods/fast-sleep.pw.toml"
hash = "b11f37dd75d669d51e711a2c55b6a1c8defa065022f99b6d30f6f40ce729b15a"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "53ca4dd806e6ae6b3d72d7707ff59c30bb6b07b7f9c2b0a2a82534c0ecfb78c4"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "225c4d26ae5d2345591ce23340cdaf9009a46a1fc46a7cb054795cd8403efe56"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "f4db358ab5081831cb84f4d81338b21f0600675ab25b13f8824deecc82d2acc8"
metafile = true

[[files]]
file = "mods/mns-moogs-nether-structures.pw.toml"
hash = "e3b2dc615d6e4dcc82d7784969a737b8d374d803fe9652682ae9a48c87e2ae10"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "30d20c16997a829c077bb4845320e01077e17aae7524ea0e8eb850112e00477d"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "344abb591cc9ec3e8a50ab00906c3f8844f0a1377a8ad492029b9fcfa3dc3379"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "44f00c1a0e3d4f8717e805c30c862a597e7856472e72637800fd1a38d73fbd08"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "08bfd9206da2a48954acae3a6083db563173def502333b6b49e7ec4cf083e231"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "93e5023b9b45c297a69ee769941b4c6a7f65eeb3f2baa569ad52f3d5aa8de398"
metafile = true

[[files]]
file = "mods/no-realms-button.pw.toml"
hash = "82c5501ec0543e249a0b3efcd3b66e517c9842aeeebd807a9c40fb7738d5a647"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
hash = "26dfaa9cd6ac317ed6a53ce7775e7ce20931bc0045b6633c9989f3b710635632"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "4f09ed451dc2215f4cb0ba6d3857d6bb61fedc05f5b12e8084db0d7417a3e395"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "b39ee5a28d5548d591e8f396d2407893affcc71470d7c058d3287039a960e55d"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "f3e9b0ac5a63f905fcf7923e71556e4ee435b858d60f05219e9ea4fcde45694a"
metafile = true

[[files]]
file = "mods/resource-config-api.pw.toml"
hash = "d99bb633768b982b8f6635fb9354b345e231dcc1bca569bb622e486c3c200b2b"
metafile = true

[[files]]
file = "mods/resource-library.pw.toml"
hash = "79dfd1825ed39daf4c5e5acf7dc1be9a0dba264f2550722eadb0013b1adbd16f"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
hash = "32c2ce6f7a0be327fb8341a82ee35768a3cecc186116d2f135e5fc95e2f56292"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "b01870e848aee7e1a2e19c6530bdd4c479b21a2f6f67134da75210844252d48f"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "3ec8292ae1ea69fee14808e0126e34d6588089e7121cf08c83024098b2d66a8a"
metafile = true

[[files]]
file = "mods/sswaystones.pw.toml"
hash = "fb961a60227c44b1d56cd9138ac08caad47a3a5a05614ec5b2d0cc82545e12ae"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "0db01c3a00fa869d75551efdd90a227b942f6ab8339426b956297072226341d6"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "c1166e4664aa67501d4daafac5e69cb29094dd46942d35e64b4d5d8a0a54decd"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "c3bdd3933c91bf17862f48396c8770fa1f4634636f01984ad9821c464539befa"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d44e2b5db1fb0c90d9ec5f25a153a437ea71c59a499491b6d639fff69cec8ba4"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "14e36ae0e9afae5ccb68646aac7979174f19ef4a32c43898392cccf5264d2e2d"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9e67328d6eaf2402b4bfc58ccc15519f41030cf3ac46af20e1ef3a72bec95909"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true

[[files]]
file = "server-icon.png"
hash = "5982a4f9e0aa2895ab359e82924682312cb8d503cda392465bcdab3fa62b470e"

[[files]]
file = "server.properties"
hash = "fe9930a585899419fa5f6b99e65bca3a56c587864e9b6b90223ea2ed0a7437ee"

[[files]]
file = "servers.dat"
hash = "8f18563bc567e7ea8955255712bb4d651c52a78fac30e5c7cd66fc4aa746b46c"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true

[[files]]
file = "shaderpacks/miniature-shader.pw.toml"
hash = "3e1dabbdda0ccd24e816482cdecf0531ebf70ee775d98457d309cab831091a76"
metafile = true

[[files]]
file = "shaderpacks/super-duper-vanilla.pw.toml"
hash = "a8d349403d1c4b03c42f1962ba993e8b3dd65b9176176eec256f3fc6cbd9f40a"
metafile = true
