name = "CircuitCraft Vanilla++ Server"
author = "SelfRef"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93fba153edc0800e89118310953b4c4bfa8eba31f54970afa035d5014c23ca0e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
